# 애플리케이션 이름
spring.application.name=hobbyVerse

# HTTP 포트 설정
server.port=8088

# JPA 설정 (Hibernate 자동 schema 업데이트)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 콘솔 설정
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# DB 설정 (H2 데이터베이스 연결)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.datasource.url=jdbc:h2:file:./data/testdb;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
spring.web.resources.static-locations=classpath:/static/,classpath:/public/

# MyBatis 설정 (매퍼 위치 설정)
mybatis.mapper-locations=classpath:/mybatis/mapper/*.xml

# MyBatis 모델 클래스 경로 설정
mybatis.type-aliases-package=com.springboot.hobbyverse.model

# 국제화 메시지 파일 설정
spring.messages.basename=titleMessage_ko_kr
spring.messages.encoding=UTF-8

# Spring Security 설정 (기본 사용자 설정)
spring.security.user.name=admin
spring.security.user.password=1234
spring.security.user.roles=ADMIN
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# OAuth2 설정 (Google OAuth)
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8088/login/oauth2/code/google
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
spring.security.oauth2.client.provider.google.jwk-set-uri=https://www.googleapis.com/oauth2/v3/certs

# JWT 설정 (시크릿 키 및 발행자 설정)
jwt.issuer=park
jwt.secretKey=HobbyVerse

spring.jackson.stream-write-constraints.max-nesting-depth=2000
